"""empty message

Revision ID: 06973a762b59
Revises: 
Create Date: 2024-06-01 02:53:07.637776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06973a762b59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('TODO', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('TODO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TODO',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', mysql.CHAR(length=1), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('TODO', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    op.drop_table('todo')
    # ### end Alembic commands ###
