version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:ucRKoZpptSQxUitPygEQPibZzIEovJnE@database:3306/todo
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=ucRKoZpptSQxUitPygEQPibZzIEovJnE
      - MYSQL_DATABASE=todo
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=todo_password
